[package]
name = "core_debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
regex = "1"
ansi_term = "0.12"
serde_json = "1"

tonic = { workspace = true }
colored = { workspace = true }
