//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "global_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_global_roles::Entity")]
    UserGlobalRoles,
}

impl Related<super::user_global_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGlobalRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
