//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod global_roles;
pub mod passwords;
pub mod project_roles;
pub mod projects;
pub mod user_global_roles;
pub mod user_project_roles;
pub mod user_projects;
pub mod users;
