//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod companies;
pub mod knowledge_base;
pub mod notes;
pub mod passwords;
pub mod projects;
pub mod roles;
pub mod sea_orm_active_enums;
pub mod subtasks;
pub mod tasks;
pub mod user_access;
pub mod user_company;
pub mod users;
