//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::companies::Entity as Companies;
pub use super::knowledge_base::Entity as KnowledgeBase;
pub use super::notes::Entity as Notes;
pub use super::passwords::Entity as Passwords;
pub use super::projects::Entity as Projects;
pub use super::roles::Entity as Roles;
pub use super::subtasks::Entity as Subtasks;
pub use super::tasks::Entity as Tasks;
pub use super::user_access::Entity as UserAccess;
pub use super::user_company::Entity as UserCompany;
pub use super::users::Entity as Users;
