//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "access_level_type")]
pub enum AccessLevelType {
    #[sea_orm(string_value = "full")]
    Full,
    #[sea_orm(string_value = "limited")]
    Limited,
    #[sea_orm(string_value = "restricted")]
    Restricted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "task_status_type")]
pub enum TaskStatusType {
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "pending")]
    Pending,
}
