[package]
name = "core_service"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "api" ]

[dependencies]
api = { path = "api" }
dotenvy = "0.15"

tokio = { version = "1.40", features = ["full"] }
