[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.40", features = ["full"] }
jsonwebtoken = "9.3"
serde = {version = "1.0", features = ["derive"] }
lazy_static = "1.5"

[build-dependencies]
tonic-build = "0.12"
